name: Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Bump version and create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: |
            # Inclua aqui os arquivos que deseja adicionar à release, por exemplo:
            # dist/*
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Descrição da release aqui

      - name: Get the new tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
